### ISSUE TITLE
User Story 1 Issue

### ISSUE THREAD

**Issue by malloryDuke** [Intro-to-SE-Lab-Fall-20/Group-10#8]
The user does not stay logged in until they press log out. As in every time the program is run the user has to log in. I am not sure if that is how we wanted it to be.

**Comment by NathanCheshire** [comment]
Given that everytime we want to send an email, we have to do something based off of the session ID which uses the user's email and password. The password should NOT be stored in plain text but instead, if you must store it at all, it should be hashed. The SHA256 output of the password, however, does us no good if we wished to create a new session upon user re-entry of straight shot. With this in mind, the best we can do is simply not "log the user out" when they press the logout button.

**Comment by NathanCheshire** [comment]
Group decision: A user will have to login and logout of their account each time. The benefit of this is the reduced chances of a password compromise. Instead we are going to associate an email address with a theme so that when the user logs in with a different email that they had logged out of, it will appear as if nothing changed.
